SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- database:ntpws

CREATE TABLE drzave (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  drzavaKod VARCHAR(2) NOT NULL DEFAULT '',
  drzavaIme VARCHAR(100) NOT NULL DEFAULT ''
) ENGINE = MYISAM DEFAULT CHARSET = utf8;

INSERT INTO drzave (id, drzavaKod, drzavaIme) VALUES
(1, 'AF', 'Afghanistan'),
(2, 'AL', 'Albania'),
(3, 'DZ', 'Algeria'),
(4, 'DS', 'American Samoa'),
(5, 'AD', 'Andorra'),
(6, 'AO', 'Angola'),
(7, 'AI', 'Anguilla'),
(8, 'AQ', 'Antarctica'),
(9, 'AG', 'Antigua and Barbuda'),
(10, 'AR', 'Argentina'),
(11, 'AM', 'Armenia'),
(12, 'AW', 'Aruba'),
(13, 'AU', 'Australia'),
(14, 'AT', 'Austria'),
(15, 'AZ', 'Azerbaijan'),
(16, 'BS', 'Bahamas'),
(17, 'BH', 'Bahrain'),
(18, 'BD', 'Bangladesh'),
(19, 'BB', 'Barbados'),
(20, 'BY', 'Belarus'),
(21, 'BE', 'Belgium'),
(22, 'BZ', 'Belize'),
(23, 'BJ', 'Benin'),
(24, 'BM', 'Bermuda'),
(25, 'BT', 'Bhutan'),
(26, 'BO', 'Bolivia'),
(27, 'BA', 'Bosnia and Herzegovina'),
(28, 'BW', 'Botswana'),
(29, 'BV', 'Bouvet Island'),
(30, 'BR', 'Brazil'),
(31, 'IO', 'British Indian Ocean Territory'),
(32, 'BN', 'Brunei Darussalam'),
(33, 'BG', 'Bulgaria'),
(34, 'BF', 'Burkina Faso'),
(35, 'BI', 'Burundi'),
(36, 'KH', 'Cambodia'),
(37, 'CM', 'Cameroon'),
(38, 'CA', 'Canada'),
(39, 'CV', 'Cape Verde'),
(40, 'KY', 'Cayman Islands'),
(41, 'CF', 'Central African Republic'),
(42, 'TD', 'Chad'),
(43, 'CL', 'Chile'),
(44, 'CN', 'China'),
(45, 'CX', 'Christmas Island'),
(46, 'CC', 'Cocos (Keeling) Islands'),
(47, 'CO', 'Colombia'),
(48, 'KM', 'Comoros'),
(49, 'CG', 'Congo'),
(50, 'CK', 'Cook Islands'),
(51, 'CR', 'Costa Rica'),
(52, 'HR', 'Croatia (Hrvatska)'),
(53, 'CU', 'Cuba'),
(54, 'CY', 'Cyprus'),
(55, 'CZ', 'Czech Republic'),
(56, 'DK', 'Denmark'),
(57, 'DJ', 'Djibouti'),
(58, 'DM', 'Dominica'),
(59, 'DO', 'Dominican Republic'),
(60, 'TP', 'East Timor'),
(61, 'EC', 'Ecuador'),
(62, 'EG', 'Egypt'),
(63, 'SV', 'El Salvador'),
(64, 'GQ', 'Equatorial Guinea'),
(65, 'ER', 'Eritrea'),
(66, 'EE', 'Estonia'),
(67, 'ET', 'Ethiopia'),
(68, 'FK', 'Falkland Islands (Malvinas)'),
(69, 'FO', 'Faroe Islands'),
(70, 'FJ', 'Fiji'),
(71, 'FI', 'Finland'),
(72, 'FR', 'France'),
(73, 'FX', 'France, Metropolitan'),
(74, 'GF', 'French Guiana'),
(75, 'PF', 'French Polynesia'),
(76, 'TF', 'French Southern Territories'),
(77, 'GA', 'Gabon'),
(78, 'GM', 'Gambia'),
(79, 'GE', 'Georgia'),
(80, 'DE', 'Germany'),
(81, 'GH', 'Ghana'),
(82, 'GI', 'Gibraltar'),
(83, 'GK', 'Guernsey'),
(84, 'GR', 'Greece'),
(85, 'GL', 'Greenland'),
(86, 'GD', 'Grenada'),
(87, 'GP', 'Guadeloupe'),
(88, 'GU', 'Guam'),
(89, 'GT', 'Guatemala'),
(90, 'GN', 'Guinea'),
(91, 'GW', 'Guinea-Bissau'),
(92, 'GY', 'Guyana'),
(93, 'HT', 'Haiti'),
(94, 'HM', 'Heard and Mc Donald Islands'),
(95, 'HN', 'Honduras'),
(96, 'HK', 'Hong Kong'),
(97, 'HU', 'Hungary'),
(98, 'IS', 'Iceland'),
(99, 'IN', 'India'),
(100, 'IM', 'Isle of Man'),
(101, 'ID', 'Indonesia'),
(102, 'IR', 'Iran (Islamic Republic of)'),
(103, 'IQ', 'Iraq'),
(104, 'IE', 'Ireland'),
(105, 'IL', 'Israel'),
(106, 'IT', 'Italy'),
(107, 'CI', 'Ivory Coast'),
(108, 'JE', 'Jersey'),
(109, 'JM', 'Jamaica'),
(110, 'JP', 'Japan'),
(111, 'JO', 'Jordan'),
(112, 'KZ', 'Kazakhstan'),
(113, 'KE', 'Kenya'),
(114, 'KI', 'Kiribati'),
(115, 'KP', 'Korea, Democratic People''s Republic of'),
(116, 'KR', 'Korea, Republic of'),
(117, 'XK', 'Kosovo'),
(118, 'KW', 'Kuwait'),
(119, 'KG', 'Kyrgyzstan'),
(120, 'LA', 'Lao People''s Democratic Republic'),
(121, 'LV', 'Latvia'),
(122, 'LB', 'Lebanon'),
(123, 'LS', 'Lesotho'),
(124, 'LR', 'Liberia'),
(125, 'LY', 'Libyan Arab Jamahiriya'),
(126, 'LI', 'Liechtenstein'),
(127, 'LT', 'Lithuania'),
(128, 'LU', 'Luxembourg'),
(129, 'MO', 'Macau'),
(130, 'MK', 'Macedonia'),
(131, 'MG', 'Madagascar'),
(132, 'MW', 'Malawi'),
(133, 'MY', 'Malaysia'),
(134, 'MV', 'Maldives'),
(135, 'ML', 'Mali'),
(136, 'MT', 'Malta'),
(137, 'MH', 'Marshall Islands'),
(138, 'MQ', 'Martinique'),
(139, 'MR', 'Mauritania'),
(140, 'MU', 'Mauritius'),
(141, 'TY', 'Mayotte'),
(142, 'MX', 'Mexico'),
(143, 'FM', 'Micronesia, Federated States of'),
(144, 'MD', 'Moldova, Republic of'),
(145, 'MC', 'Monaco'),
(146, 'MN', 'Mongolia'),
(147, 'ME', 'Montenegro'),
(148, 'MS', 'Montserrat'),
(149, 'MA', 'Morocco'),
(150, 'MZ', 'Mozambique'),
(151, 'MM', 'Myanmar'),
(152, 'NA', 'Namibia'),
(153, 'NR', 'Nauru'),
(154, 'NP', 'Nepal'),
(155, 'NL', 'Netherlands'),
(156, 'AN', 'Netherlands Antilles'),
(157, 'NC', 'New Caledonia'),
(158, 'NZ', 'New Zealand'),
(159, 'NI', 'Nicaragua'),
(160, 'NE', 'Niger'),
(161, 'NG', 'Nigeria'),
(162, 'NU', 'Niue'),
(163, 'NF', 'Norfolk Island'),
(164, 'MP', 'Northern Mariana Islands'),
(165, 'NO', 'Norway'),
(166, 'OM', 'Oman'),
(167, 'PK', 'Pakistan'),
(168, 'PW', 'Palau'),
(169, 'PS', 'Palestine'),
(170, 'PA', 'Panama'),
(171, 'PG', 'Papua New Guinea'),
(172, 'PY', 'Paraguay'),
(173, 'PE', 'Peru'),
(174, 'PH', 'Philippines'),
(175, 'PN', 'Pitcairn'),
(176, 'PL', 'Poland'),
(177, 'PT', 'Portugal'),
(178, 'PR', 'Puerto Rico'),
(179, 'QA', 'Qatar'),
(180, 'RE', 'Reunion'),
(181, 'RO', 'Romania'),
(182, 'RU', 'Russian Federation'),
(183, 'RW', 'Rwanda'),
(184, 'KN', 'Saint Kitts and Nevis'),
(185, 'LC', 'Saint Lucia'),
(186, 'VC', 'Saint Vincent and the Grenadines'),
(187, 'WS', 'Samoa'),
(188, 'SM', 'San Marino'),
(189, 'ST', 'Sao Tome and Principe'),
(190, 'SA', 'Saudi Arabia'),
(191, 'SN', 'Senegal'),
(192, 'RS', 'Serbia'),
(193, 'SC', 'Seychelles'),
(194, 'SL', 'Sierra Leone'),
(195, 'SG', 'Singapore'),
(196, 'SK', 'Slovakia'),
(197, 'SI', 'Slovenia'),
(198, 'SB', 'Solomon Islands'),
(199, 'SO', 'Somalia'),
(200, 'ZA', 'South Africa'),
(201, 'GS', 'South Georgia South Sandwich Islands'),
(202, 'ES', 'Spain'),
(203, 'LK', 'Sri Lanka'),
(204, 'SH', 'St. Helena'),
(205, 'PM', 'St. Pierre and Miquelon'),
(206, 'SD', 'Sudan'),
(207, 'SR', 'Suriname'),
(208, 'SJ', 'Svalbard and Jan Mayen Islands'),
(209, 'SZ', 'Swaziland'),
(210, 'SE', 'Sweden'),
(211, 'CH', 'Switzerland'),
(212, 'SY', 'Syrian Arab Republic'),
(213, 'TW', 'Taiwan'),
(214, 'TJ', 'Tajikistan'),
(215, 'TZ', 'Tanzania, United Republic of'),
(216, 'TH', 'Thailand'),
(217, 'TG', 'Togo'),
(218, 'TK', 'Tokelau'),
(219, 'TO', 'Tonga'),
(220, 'TT', 'Trinidad and Tobago'),
(221, 'TN', 'Tunisia'),
(222, 'TR', 'Turkey'),
(223, 'TM', 'Turkmenistan'),
(224, 'TC', 'Turks and Caicos Islands'),
(225, 'TV', 'Tuvalu'),
(226, 'UG', 'Uganda'),
(227, 'UA', 'Ukraine'),
(228, 'AE', 'United Arab Emirates'),
(229, 'GB', 'United Kingdom'),
(230, 'US', 'United States'),
(231, 'UM', 'United States minor outlying islands'),
(232, 'UY', 'Uruguay'),
(233, 'UZ', 'Uzbekistan'),
(234, 'VU', 'Vanuatu'),
(235, 'VA', 'Vatican City State'),
(236, 'VE', 'Venezuela'),
(237, 'VN', 'Vietnam'),
(238, 'VG', 'Virgin Islands (British)'),
(239, 'VI', 'Virgin Islands (U.S.)'),
(240, 'WF', 'Wallis and Futuna Islands'),
(241, 'EH', 'Western Sahara'),
(242, 'YE', 'Yemen'),
(243, 'ZR', 'Zaire'),
(244, 'ZM', 'Zambia'),
(245, 'ZW', 'Zimbabwe');

DROP TABLE korisnik;
CREATE TABLE korisnik (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ime VARCHAR(255) NOT NULL,
	prezime VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	korisnickoIme VARCHAR(255) NOT NULL,
	lozinka VARCHAR(255) NOT NULL,
	drzava CHAR(2) NOT NULL,
	grad VARCHAR(255) NOT NULL,
	ulica VARCHAR(255) NOT NULL,
	datumRodenja DATE NOT NULL,
	arhiva ENUM('Y', 'N') NOT NULL DEFAULT 'N',
	odobren ENUM('Y', 'N') NOT NULL DEFAULT 'N',
	id_role INT(1) DEFAULT '3',
	KEY fk_role_korisnik(id_role), 
	CONSTRAINT fk_role_korisnik FOREIGN KEY (id_role)
	REFERENCES ROLE(id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB DEFAULT CHARSET = cp1250;

INSERT INTO korisnik (ime, prezime, email, korisnickoIme, lozinka, drzava, grad, ulica, datumRodenja, arhiva, odobren, id_role) VALUES
('Ruža', 'Kelava', 'rkelava@tvz.hr', 'rkelava', 'lozinka', 'BA', 'Livno', 'Cefin brig', '1997-04-24','N','Y',1),
('Zlatko', 'Dalic', 'zlatkodalic@gmail.com', 'zlatkodalic', 'lozinka', 'BA', 'Livno', 'Gorica', '1967-05-01','Y','Y',2),
('Maja', 'Krpelnik', 'majakrpelnik@gmail.com', 'majak', 'lozinka', 'HR', 'Zagreb', 'Samoborska', '2005-10-28','N','N',3);

CREATE TABLE `role`(
	id INT(1) NOT NULL PRIMARY KEY,
	naziv VARCHAR(20) NOT NULL
)ENGINE = INNODB DEFAULT CHARSET = cp1250;

INSERT INTO ROLE(id, naziv) VALUES 
(1, 'administrator'), 
(2, 'editor'),
(3, 'user');

CREATE TABLE novosti (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  naslov VARCHAR(255) NOT NULL,
  opis TEXT NOT NULL,
  datum TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  arhiva ENUM('Y','N') NOT NULL,
  odobreno ENUM('Y','N') NOT NULL DEFAULT 'Y'
) ENGINE = INNODB DEFAULT CHARSET = cp1250;


INSERT INTO novosti (id, naslov, opis, datum, arhiva) VALUES
(1,'Livnjak Nino Šeremet prvak Europe u taekwondo-u', 'Mladi taekwondoaš, član TKD Magone Livno Nino Šeremet osvojio je naslov prvaka Europe u kadetskoj konkurenciji. Šeremet je osvojio zlatnu medalju na Europskom kadetskom prvenstvu na Malti u kategoriji + 65 kilograma.
  Ostvario je pobjede nad tri predstavnika Grčke te Švedske te došao do najsjajnijeg odličja. "Ponosan sam i presretan. Hvala svima na podršci i čestitkama. Zahvaljujem se Taekwondo savezu BiH, TKD klubu Magone i svojoj obitelji. Vjerovali smo u ovaj uspjeh i naporno radili da bi došli do ovoga", kazao je Nino Šeremet.
  Prethodno je članica  Sara Džafić osvojila brončanu medalju u konkurenciji kadetkinja.', '2022-11-27 15:14:11', 'N'),
(2, 'Prikupljeno 13.000 KM za novu kuhinju Srednje strukovne škole u Livnu', '“Generacija budućnosti” naziv je humanitarne večere čiji je cilj prikupljanje sredstava za kupovinu nove moderne kuhinjske opreme za izvođenje praktične nastave učenika ugostiteljskog smjera livanjske Srednje strukovne škole. Za 100 Livnjaka koji su kupili ulaznicu večeru je s učenicima kuhalo pet poznatih šefova iz Hrvatske i Bosne i Hercegovine, a Livno još jednom pokazalo veliko srce. Iza savršene večere od pet slijedova koje su konobari ponosno iznosili, u kuhinji užurbanost, znoj, strepnja. Vrhunski šefovi su dva dana nesebično dijelili tajne svog kuharskog umijeća, učenici ih upijali i vrijedno radili za novu kuhinju.Divno iskustvo zato što sam puno toga naučila. Vjerojatno opet bih ovo sve ponovila, ali bilo je teško stajati na nogama cijeli dan”, priča Filipa Baković, učenica iz Tomislavgrada. Prenosi Federalna.“Prilika da naučim nešto više u toj kuhinji da mogu dalje ići”, kaže Paola Mihaljević, učenica iz Livna.
     “Ova nova kuhinja stvarno bi nam bila dobra zato što, kad otvaramo nešto izgleda kao da će nešto puknut”, dodaje Filipa. Glavni „krivac“ za ovu pozitivnu priču prošle godine je s kolegom radio edukaciju za kuhare. “Onda smo vidjeli da je loša bila situacija u samoj opremi kuhinje pa smo dali obećanje da ćemo se vratiti da napravimo nešto”, istakao je Tomislav Trboglav, suvlasnik i glavni šef restorana Chevos u Zagrebu. “Da imamo kvalitetne, školovane kuhare, to je svima nama koji se bavimo turizmom i ugostiteljstvom ovdje u našem gradu i kantonu, tako da na ovaj način napravimo sebi neku generaciju budućnosti”, navodi Marin Mamuza, vlasnik TA Continental Adventure Livno. “Učenici su fenomenalni, prihvatili su te neke nove ideje koje su vrhunski naši kuhari, stručnjaci koji su tu večeras, prihvatili su sve na najbolji mogući način i Livno ima dobru i svijetlu budućnost što se tiče gastronomije i kulinarstva”, kazao je direktor hotela Novitas u Livnu Mirko Brdar. Trud se isplatio. 
     Prikupljeno je 13 tisuća maraka, tako da će s novom opremom ova školska kuhinja, u kojoj su mnogi učenici napravili svoja prva samostalna jela, ovoj, a i budućim generacijama, pružiti još bolju i suvremeniju obuku. ','2022-11-29 22:00:00', 'N'),
(3, 'Izabran novi predsjednik Mladeži HDZ-a 1990 u Livnu', 'Nakon održane izborne skupštine, jučer je uslijedila prva sjednica Gradskog odbora Mladeži HDZ 1990 Livno. U novi saziv Gradskog odbora izabrani su: Mate Vukadin, Karolina Pavlinović, Stipe Badrov, Branka Mamić, Rafael Rimac, Mislav Mišković, Domagoj Mamić, Anđela Damjanović, Jure Cvrlje, Josip Perković, Mate Vrdoljak, Katarina Suša, Mirna Marinčić, Drago Ćavar, Marijana Vrdoljak, Iva Knežević, Ivana Miloloža, Tomislav Sučić, Anita Vidović i Anton Barać. Na prvoj sjednici Gradskog odbora izabrano je novo vodstvo Mladeži HDZ 1990 Livno koje će činiti Mislav Mišković kao predsjednik, Branka Mamić i Stipe Badrov kao dopredsjednici i Domagoj Mamić koji je izabran za tajnika Gradskog odbora.
     Novoizabrani predsjednik zahvalio je članovima Gradskog odbora na povjerenju, te prezentirao program rada za 2023. godinu. Zahvalio je također i prethodnom predsjedniku Mati Vukadinu na dosadašnjem radu.','2022-11-23 04:41:40', 'N'),
(4, 'Gradonačelnik Livna posjetio Livnjake u Kanadi', 'Grad Livno prepoznao je važnost suradnje s livanjskom dijasporom, a kako bi se uspostavila što bolja međusobna komunikacija i umrežavanje gradonačelnik, Darko Čondrić, boravio je u radnoj posjeti zajednici Livnjaka u Kanadi, točnije u pokrajini Ontario, od 3. do 8. studenog.
    Tom prilikom sudjelovao je i na Livanjskoj noći koja je održana u subotu 5. studenog u Oakville-u. Održani su i sastanci s predstavnicima Društva Livnjaka Južnog Ontaria koji su i organizatori Livanjske noći.Prilikom posjeta Hrvatskom nacionalnom centru u Niagari, gradonačelnik se sastao i s Državnim tajnikom Središnjeg državnog ureda za Hrvate izvan Republike Hrvatske, Zvonkom Milasom, te s   izvanrednim i opunomoćenim veleposlanikom Republike Hrvatske u Kanadi Vicom Skračićem i Antom Jovićev, Generalnim konzulom Republike Hrvatske u Mississaugi.U nedjelju, 6. studenog, gradonačelnik je bio  posjetu Norvalu – Hrvatskoj župi Kraljice Mira – Hrvatskom franjevačkom središtu i susreo se s Livnjacima koji pripadaju toj župi. Posjetio je i Hrvatski sportski i društveni centar Hamilton koji je osnovan za promicanje sporta i drugih oblika hrvatske kulture za dobrobit hrvatske zajednice u Južnom Ontariu, gdje se također okuplja i veći dio naših Livnjaka.
    Zadnji dan posjete Kanadi, gradonačelnik i predstavnici Društva Livnjaka Južnog Ontaria sastali su se s Generalnim konzulom Republike Hrvatske u Mississaugi, Antom Jovićem.
     ','2022-11-25 09:05:05', 'N');

CREATE TABLE slike (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	naziv VARCHAR(255) NOT NULL,
	opis VARCHAR(255) NOT NULL,
	id_novosti INT(11) NOT NULL,
	KEY fk_slike_novosti(id_novosti), 
	CONSTRAINT fk_slike_novosti FOREIGN KEY (id_novosti)
	REFERENCES novosti(id) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE = INNODB DEFAULT CHARSET = cp1250;

INSERT INTO slike (naziv, opis, id_novosti) VALUES
('NinoŠeremet_prvakEurope1.jpg', 'Niko Šeremet', 1),
('NinoŠeremet_prvakEurope2.jpg', 'Niko Šeremet', 1),
('novosti_NovaKuhinja.jpg', 'SŠ- nova kuhinja', 2),
('noviPredsjetnikmladezi.jpg', 'Predsjetnik mladezi', 3),
('noviPredsjetnikmladezi.jpg', 'Predsjetnik mladezi', 3),
('LivnoKanada.jpg', 'Livanjski gradonačelnik u Kanadi', 4);

SELECT * FROM novosti;


SELECT * FROM korisnik;

UPDATE korisnik
SET arhiva='Y', id_role=1
WHERE id=12;

UPDATE korisnik
SET odobren='Y'
WHERE id=12;


